const mongoose = require('mongoose');

const dailyTopicSchema = new mongoose.Schema({
    title: {
        type: String,
        required: true
    },
    content: {
        type: String,
        required: true
    },
    subject: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Subject',
        required: true
    },
    publishDate: {
        type: Date,
        default: Date.now,
        required: true
    },
    // Estimated time to read in minutes
    readTime: {
        type: Number,
        default: 2
    },
    difficulty: {
        type: String,
        enum: ['beginner', 'intermediate', 'advanced'],
        default: 'intermediate'
    },
    tags: [{
        type: String
    }],
    // Optional quiz related to the daily topic (quick check)
    relatedQuiz: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Quiz'
    },
    // Track how many users have viewed this topic
    viewCount: {
        type: Number,
        default: 0
    },
    // Track how many users have completed the quick quiz
    completionCount: {
        type: Number,
        default: 0
    },
    // Links to related topics for those who want to explore further
    relatedTopics: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Topic'
    }],
    // If this topic was generated by AI
    isGeneratedByAI: {
        type: Boolean,
        default: false
    },
    // Creator of the topic (admin or system)
    createdBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    }
}, { timestamps: true });

const DailyTopic = mongoose.model('DailyTopic', dailyTopicSchema);

module.exports = DailyTopic; 